FROM amazoncorretto:17-alpine-jdk
MAINTAINER Leonardo Dantas
COPY target/app-testes-carga-java-0.0.1-SNAPSHOT.jar app-testes-carga-java-0.0.1.jar
ENTRYPOINT ["java","-jar","/app-testes-carga-java-0.0.1.jar"]