version: '3'
services:
  testes-carga-mongodb:
    networks:
      - rede-docker-compose
    image: mongo:4.2.23
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=leonardo
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - /private/var/lib/mongodb:/var/lib/mongodb
#    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '0.75GB'
  testes-carga-java:
    networks:
      - rede-docker-compose
    depends_on:
      - testes-carga-mongodb
    build:
      ./app-testes-carga-java/
    ports:
      - "8081:8080"
    restart: always
    #    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '0.75GB'
  redis:
    image: redis
    command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.37GB'
networks:
  rede-docker-compose:
    driver: bridge