version: '3'
services:
  testes-carga-postgres:
    container_name: testes-carga-postgres
    networks:
      - rede-docker-compose
    restart: always
    image: postgres
    environment:
      DATABASE_HOST: "127.0.0.1"
      POSTGRES_USER: "leonardo"
      POSTGRES_DB: "testesCarga"
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
#    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '0.75GB'
  testes-carga-mongodb:
    networks:
      - rede-docker-compose
    image: mongo:4.2.23
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=leonardo
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - /private/var/lib/mongodb:/var/lib/mongodb
#    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '0.75GB'
  testes-carga-java:
    networks:
      - rede-docker-compose
    depends_on:
      - testes-carga-postgres
      - testes-carga-mongodb
    build:
      ./app-testes-carga-java/
    ports:
      - "8081:8080"
    restart: always
    #    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '0.75GB'
networks:
  rede-docker-compose:
    driver: bridge