version: '3'
services:
  loadbalance:
    build:
      context: nginx
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    networks:
      - rede-docker-compose
    depends_on:
      - testes-carga-java-1
      - testes-carga-java-2
  testes-carga-mongodb:
    networks:
      - rede-docker-compose
    image: mongo:4.2.23
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=leonardo
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - /private/var/lib/mongodb:/var/lib/mongodb
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '0.75GB'
  testes-carga-java-1:
    networks:
      - rede-docker-compose
    depends_on:
      - testes-carga-mongodb
    build:
      ./app-testes-carga-java/
    ports:
      - "8081:8080"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '0.75GB'
  testes-carga-java-2:
    networks:
      - rede-docker-compose
    depends_on:
      - testes-carga-mongodb
    build:
      ./app-testes-carga-java/
    ports:
      - "8082:8080"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '0.75GB'
networks:
  rede-docker-compose:
    driver: bridge