spring:
  application:
    name: app-testes-carga-java
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      auto-index-creation: true
      uri: "mongodb://leonardo:123456@testes-carga-mongodb:27017/testesCarga?authSource=admin"
  kafka:
    producer:
      acks: -1
      bootstrap-servers: teste-carga-kafka:29092
    topics:
      create:
        product: "create.product.kafka"