spring:
  application:
    name: app-testes-carga-java
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      auto-index-creation: true
      uri: "mongodb://leonardo:123456@localhost:27017/testesCarga?authSource=admin"